language: objective-c
osx_image: xcode8.2
xcode_project: Photos.xcodeproj
xcode_scheme: Photos, OCLint
xcode_sdk: iphonesimulator9.0

install: xcodebuild build -alltargets | xcpretty
script: true

notifications:
  email:
    on_failure: change
